### ISSUE TITLE
Please remove Adam from delegates selection

### ISSUE THREAD

**Issue by adamsteeber** [novasamatech/opengov-delegate-registry#104]
Hello,

I would like to be removed as a delegate on Kusama. Please let me know if you need any kind of on-chain confirmation for this request

Thank you,

Adam

**Comment by SnotnoseGOO104** [comment]
Why bro

**Comment by stepanLav** [comment]
Hello @adamsteeber!
Could you please specify which addresses you want to remove?

**Comment by adamsteeber** [comment]
GqC37KSFFeGAoL7YxSeP1YDwr85WJvLmDDQiSaprTDAm8Jj

Here it is in kusama.json: https://github.com/novasamatech/opengov-delegate-registry/blob/5ce6816be66b6826a594d824bb8223589d05c179/registry/kusama.json#L59
